/********************************************************************
* CDCDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CDCDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevCDCDict();
extern G__DLLEXPORT void G__set_cpp_environmentCDCDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableCDCDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceCDCDict();
extern G__DLLEXPORT void G__cpp_setup_typetableCDCDict();
extern G__DLLEXPORT void G__cpp_setup_memvarCDCDict();
extern G__DLLEXPORT void G__cpp_setup_globalCDCDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncCDCDict();
extern G__DLLEXPORT void G__cpp_setup_funcCDCDict();
extern G__DLLEXPORT void G__cpp_setupCDCDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CommonDeviceController.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CDCDictLN_TClass;
extern G__linked_taginfo G__CDCDictLN_TBuffer;
extern G__linked_taginfo G__CDCDictLN_TMemberInspector;
extern G__linked_taginfo G__CDCDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__CDCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CDCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDCDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__CDCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__CDCDictLN_TList;
extern G__linked_taginfo G__CDCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CDCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDCDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__CDCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__CDCDictLN_TQObjSender;
extern G__linked_taginfo G__CDCDictLN_CommonDeviceController;

/* STUB derived class for protected member access */
