/********************************************************************
* chillerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error chillerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevchillerDict();
extern G__DLLEXPORT void G__set_cpp_environmentchillerDict();
extern G__DLLEXPORT void G__cpp_setup_tagtablechillerDict();
extern G__DLLEXPORT void G__cpp_setup_inheritancechillerDict();
extern G__DLLEXPORT void G__cpp_setup_typetablechillerDict();
extern G__DLLEXPORT void G__cpp_setup_memvarchillerDict();
extern G__DLLEXPORT void G__cpp_setup_globalchillerDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncchillerDict();
extern G__DLLEXPORT void G__cpp_setup_funcchillerDict();
extern G__DLLEXPORT void G__cpp_setupchillerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "chiller_new.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__chillerDictLN_TClass;
extern G__linked_taginfo G__chillerDictLN_TBuffer;
extern G__linked_taginfo G__chillerDictLN_TMemberInspector;
extern G__linked_taginfo G__chillerDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__chillerDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__chillerDictLN_string;
extern G__linked_taginfo G__chillerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__chillerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__chillerDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__chillerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__chillerDictLN_TList;
extern G__linked_taginfo G__chillerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__chillerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__chillerDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__chillerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__chillerDictLN_TQObjSender;
extern G__linked_taginfo G__chillerDictLN_TThread;
extern G__linked_taginfo G__chillerDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__chillerDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__chillerDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR;
extern G__linked_taginfo G__chillerDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__chillerDictLN_Chiller_Medingen_C20;

/* STUB derived class for protected member access */
