/********************************************************************
* KeithDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error KeithDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevKeithDict();
extern G__DLLEXPORT void G__set_cpp_environmentKeithDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableKeithDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceKeithDict();
extern G__DLLEXPORT void G__cpp_setup_typetableKeithDict();
extern G__DLLEXPORT void G__cpp_setup_memvarKeithDict();
extern G__DLLEXPORT void G__cpp_setup_globalKeithDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncKeithDict();
extern G__DLLEXPORT void G__cpp_setup_funcKeithDict();
extern G__DLLEXPORT void G__cpp_setupKeithDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Keithley2410.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__KeithDictLN_TClass;
extern G__linked_taginfo G__KeithDictLN_TBuffer;
extern G__linked_taginfo G__KeithDictLN_TMemberInspector;
extern G__linked_taginfo G__KeithDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__KeithDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__KeithDictLN_string;
extern G__linked_taginfo G__KeithDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__KeithDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KeithDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__KeithDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__KeithDictLN_TList;
extern G__linked_taginfo G__KeithDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__KeithDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KeithDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__KeithDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__KeithDictLN_TQObjSender;
extern G__linked_taginfo G__KeithDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__KeithDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KeithDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR;
extern G__linked_taginfo G__KeithDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__KeithDictLN_Keithley2410;

/* STUB derived class for protected member access */
