/********************************************************************
* SerialComDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SerialComDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevSerialComDict();
extern G__DLLEXPORT void G__set_cpp_environmentSerialComDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableSerialComDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceSerialComDict();
extern G__DLLEXPORT void G__cpp_setup_typetableSerialComDict();
extern G__DLLEXPORT void G__cpp_setup_memvarSerialComDict();
extern G__DLLEXPORT void G__cpp_setup_globalSerialComDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncSerialComDict();
extern G__DLLEXPORT void G__cpp_setup_funcSerialComDict();
extern G__DLLEXPORT void G__cpp_setupSerialComDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SerialCom.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SerialComDictLN_TClass;
extern G__linked_taginfo G__SerialComDictLN_TBuffer;
extern G__linked_taginfo G__SerialComDictLN_TMemberInspector;
extern G__linked_taginfo G__SerialComDictLN_TString;
extern G__linked_taginfo G__SerialComDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__SerialComDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__SerialComDictLN_string;
extern G__linked_taginfo G__SerialComDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SerialComDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SerialComDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__SerialComDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__SerialComDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SerialComDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SerialComDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__SerialComDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__SerialComDictLN_TMutex;
extern G__linked_taginfo G__SerialComDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__SerialComDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SerialComDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR;
extern G__linked_taginfo G__SerialComDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__SerialComDictLN_SerialCom;

/* STUB derived class for protected member access */
