//
// File generated by C:\ROOT-5.34\\bin\rootcint.exe at Mon Aug 19 14:38:58 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TempDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TempDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TempInterlock_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TempInterlock(void *p = 0);
   static void *newArray_TempInterlock(Long_t size, void *p);
   static void delete_TempInterlock(void *p);
   static void deleteArray_TempInterlock(void *p);
   static void destruct_TempInterlock(void *p);
   static void streamer_TempInterlock(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TempInterlock*)
   {
      ::TempInterlock *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TempInterlock >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TempInterlock", ::TempInterlock::Class_Version(), "./TempInterlock.h", 20,
                  typeid(::TempInterlock), DefineBehavior(ptr, ptr),
                  &::TempInterlock::Dictionary, isa_proxy, 0,
                  sizeof(::TempInterlock) );
      instance.SetNew(&new_TempInterlock);
      instance.SetNewArray(&newArray_TempInterlock);
      instance.SetDelete(&delete_TempInterlock);
      instance.SetDeleteArray(&deleteArray_TempInterlock);
      instance.SetDestructor(&destruct_TempInterlock);
      instance.SetStreamerFunc(&streamer_TempInterlock);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TempInterlock*)
   {
      return GenerateInitInstanceLocal((::TempInterlock*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TempInterlock*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TempInterlock::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TempInterlock::Class_Name()
{
   return "TempInterlock";
}

//______________________________________________________________________________
const char *TempInterlock::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TempInterlock*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TempInterlock::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TempInterlock*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TempInterlock::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TempInterlock*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TempInterlock::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TempInterlock*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TempInterlock::Streamer(TBuffer &R__b)
{
   // Stream an object of class TempInterlock.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      fQObject.Streamer(R__b);
      { TString R__str; R__str.Streamer(R__b); InterlockReadSettings = R__str.Data(); }
      R__b >> lastTime_ReadSettings;
      { TString R__str; R__str.Streamer(R__b); CurrentTempReadout = R__str.Data(); }
      R__b >> lastTime_TempReadout;
      R__b.CheckByteCount(R__s, R__c, TempInterlock::IsA());
   } else {
      R__c = R__b.WriteVersion(TempInterlock::IsA(), kTRUE);
      fQObject.Streamer(R__b);
      { TString R__str = InterlockReadSettings.c_str(); R__str.Streamer(R__b);}
      R__b << lastTime_ReadSettings;
      { TString R__str = CurrentTempReadout.c_str(); R__str.Streamer(R__b);}
      R__b << lastTime_TempReadout;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TempInterlock::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TempInterlock.
      typedef ::TempInterlock msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "InterlockReadSettings", (void*)&InterlockReadSettings);
      R__insp.InspectMember("string", (void*)&InterlockReadSettings, "InterlockReadSettings.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lastTime_ReadSettings", &lastTime_ReadSettings);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "CurrentTempReadout", (void*)&CurrentTempReadout);
      R__insp.InspectMember("string", (void*)&CurrentTempReadout, "CurrentTempReadout.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lastTime_TempReadout", &lastTime_TempReadout);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TempInterlock(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TempInterlock : new ::TempInterlock;
   }
   static void *newArray_TempInterlock(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TempInterlock[nElements] : new ::TempInterlock[nElements];
   }
   // Wrapper around operator delete
   static void delete_TempInterlock(void *p) {
      delete ((::TempInterlock*)p);
   }
   static void deleteArray_TempInterlock(void *p) {
      delete [] ((::TempInterlock*)p);
   }
   static void destruct_TempInterlock(void *p) {
      typedef ::TempInterlock current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TempInterlock(TBuffer &buf, void *obj) {
      ((::TempInterlock*)obj)->::TempInterlock::Streamer(buf);
   }
} // end of namespace ROOT for class ::TempInterlock

/********************************************************
* TempDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTempDict();

extern "C" void G__set_cpp_environmentTempDict() {
  G__add_ipath("../../include");
  G__cpp_reset_tagtableTempDict();
}
#include <new>
extern "C" int G__cpp_dllrevTempDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TempInterlock */
static int G__TempDict_270_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TempInterlock*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((TempInterlock*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((TempInterlock*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((TempInterlock*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((TempInterlock*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((TempInterlock*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TempInterlock* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TempInterlock[n];
     } else {
       p = new((void*) gvp) TempInterlock[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TempInterlock;
     } else {
       p = new((void*) gvp) TempInterlock;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TempDictLN_TempInterlock));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TempInterlock* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TempInterlock((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TempInterlock((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TempDictLN_TempInterlock));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getTemp((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((TempInterlock*) G__getstructoffset())->getTempVector();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((TempInterlock*) G__getstructoffset())->getInterlockReadSettings();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getLowerTempHybrid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getHigherTempHybrid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TempInterlock*) G__getstructoffset())->getNumberOfHybridNTCs());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getLowerTempUserNTC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getHigherTempUserNTC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TempInterlock*) G__getstructoffset())->getNumberOfUserNTCs());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getLowerTempSHT7x());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getHigherTempSHT7x());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getLowerHumiditySHT7x());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TempInterlock*) G__getstructoffset())->getHigherHumiditySHT7x());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TempInterlock*) G__getstructoffset())->getNumberOfSHT7xSensors());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->InterlockOutputEnable());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->InterlockOutputDisable());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->InterlockOutputSetStatus((bool) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setLowerTempHybrid((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setHigherTempHybrid((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setLowerTempUserNTC((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setHigherTempUserNTC((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setLowerTempSHT7x((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setHigherTempSHT7x((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setLowerHumiditySHT7x((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TempInterlock*) G__getstructoffset())->setHigherHumiditySHT7x((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TempInterlock::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TempInterlock::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TempInterlock::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TempInterlock::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TempInterlock*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TempInterlock*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TempInterlock::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TempInterlock::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TempInterlock::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TempDict_270_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TempInterlock::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TempInterlock G__TTempInterlock;
static int G__TempDict_270_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TempInterlock*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TempInterlock*) (soff+(sizeof(TempInterlock)*i)))->~G__TTempInterlock();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TempInterlock*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TempInterlock*) (soff))->~G__TTempInterlock();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TempInterlock */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTempDict {
 public:
  G__Sizep2memfuncTempDict(): p(&G__Sizep2memfuncTempDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTempDict::*p)();
};

size_t G__get_sizep2memfuncTempDict()
{
  G__Sizep2memfuncTempDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTempDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTempDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("iterator<iterator_traits<string::iterator>::iterator_category,iterator_traits<string::iterator>::value_type,iterator_traits<string::iterator>::difference_type,iterator_traits<string::iterator>::pointer,iterator_traits<string::iterator>::reference>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long,char*>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<string::const_iterator>::iterator_category,iterator_traits<string::const_iterator>::value_type,iterator_traits<string::const_iterator>::difference_type,iterator_traits<string::const_iterator>::pointer,iterator_traits<string::const_iterator>::reference>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TempInterlock */
static void G__setup_memvarTempInterlock(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TempDictLN_TempInterlock));
   { TempInterlock *p; p=(TempInterlock*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TempDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TempDictLN_string),-1,-1,4,"InterlockReadSettings=",0,(char*)NULL);
   G__memvar_setup((void*)0,110,0,0,-1,-1,-1,4,"lastTime_ReadSettings=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TempDictLN_string),-1,-1,4,"CurrentTempReadout=",0,(char*)NULL);
   G__memvar_setup((void*)0,110,0,0,-1,-1,-1,4,"lastTime_TempReadout=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TempDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTempDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTempInterlock(void) {
   /* TempInterlock */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TempDictLN_TempInterlock));
   G__memfunc_setup("GetListOfSignals",1602,G__TempDict_270_0_1, 85, G__get_linked_tagnum(&G__TempDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__TempDict_270_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__TempDict_270_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__TempDict_270_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__TempDict_270_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__TempDict_270_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TempDict_270_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__TempDict_270_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__TempDict_270_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__TempDict_270_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TempInterlock",1345,G__TempDict_270_0_26, 105, G__get_linked_tagnum(&G__TempDictLN_TempInterlock), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TempInterlock",1345,G__TempDict_270_0_27, 105, G__get_linked_tagnum(&G__TempDictLN_TempInterlock), -1, 0, 1, 1, 1, 0, "C - - 10 - Port", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTemp",726,G__TempDict_270_0_28, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTempVector",1353,G__TempDict_270_0_29, 117, G__get_linked_tagnum(&G__TempDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getInterlockReadSettings",2488,G__TempDict_270_0_30, 117, G__get_linked_tagnum(&G__TempDictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getLowerTempHybrid",1857,G__TempDict_270_0_31, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getHigherTempHybrid",1935,G__TempDict_270_0_32, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNumberOfHybridNTCs",2072,G__TempDict_270_0_33, 105, -1, -1, 0, 0, 1, 1, 0, "", "Number of sensors enabled on the Hybrid", (void*) NULL, 0);
   G__memfunc_setup("getLowerTempUserNTC",1891,G__TempDict_270_0_34, 100, -1, -1, 0, 0, 1, 1, 0, "", "Lower temperature limit for the user NTCs", (void*) NULL, 0);
   G__memfunc_setup("getHigherTempUserNTC",1969,G__TempDict_270_0_35, 100, -1, -1, 0, 0, 1, 1, 0, "", "Higher temperature limit for user NTCs", (void*) NULL, 0);
   G__memfunc_setup("getNumberOfUserNTCs",1877,G__TempDict_270_0_36, 105, -1, -1, 0, 0, 1, 1, 0, "", "Number of enabled user NTCs", (void*) NULL, 0);
   G__memfunc_setup("getLowerTempSHT7x",1661,G__TempDict_270_0_37, 100, -1, -1, 0, 0, 1, 1, 0, "", "Lower temperature limit for the SHT 7x RH/T sensor", (void*) NULL, 0);
   G__memfunc_setup("getHigherTempSHT7x",1739,G__TempDict_270_0_38, 100, -1, -1, 0, 0, 1, 1, 0, "", "Higher temperature limit for SHT 7x RH/T sensor", (void*) NULL, 0);
   G__memfunc_setup("getLowerHumiditySHT7x",2100,G__TempDict_270_0_39, 100, -1, -1, 0, 0, 1, 1, 0, "", "Lower relative humidity limit for SHT7x sensor", (void*) NULL, 0);
   G__memfunc_setup("getHigherHumiditySHT7x",2178,G__TempDict_270_0_40, 100, -1, -1, 0, 0, 1, 1, 0, "", "Higher relative humidity limit for SHT7x sensor", (void*) NULL, 0);
   G__memfunc_setup("getNumberOfSHT7xSensors",2281,G__TempDict_270_0_41, 105, -1, -1, 0, 0, 1, 1, 0, "", "Number of enabled Sensors", (void*) NULL, 0);
   G__memfunc_setup("InterlockOutputEnable",2179,G__TempDict_270_0_42, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InterlockOutputDisable",2288,G__TempDict_270_0_43, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InterlockOutputSetStatus",2540,G__TempDict_270_0_44, 103, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - newstatus", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLowerTempHybrid",1869,G__TempDict_270_0_45, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - temp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setHigherTempHybrid",1947,G__TempDict_270_0_46, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - temp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLowerTempUserNTC",1903,G__TempDict_270_0_47, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - temp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setHigherTempUserNTC",1981,G__TempDict_270_0_48, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - temp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLowerTempSHT7x",1673,G__TempDict_270_0_49, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - temp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setHigherTempSHT7x",1751,G__TempDict_270_0_50, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - temp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLowerHumiditySHT7x",2112,G__TempDict_270_0_51, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - humidity", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setHigherHumiditySHT7x",2190,G__TempDict_270_0_52, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - humidity", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("queryCommand",1269,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__TempDictLN_string), -1, 0, 1, 1, 4, 0, "u 'string' - 0 - command", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getSetting",1054,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__TempDictLN_string), -1, 0, 1, 1, 4, 0, "u 'string' - 0 - setting", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setValue",841,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 2, 1, 4, 0, 
"u 'string' - 0 - command d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TempDict_270_0_56, 85, G__get_linked_tagnum(&G__TempDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TempInterlock::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TempDict_270_0_57, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TempInterlock::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TempDict_270_0_58, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TempInterlock::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TempDict_270_0_59, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TempInterlock::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__TempDict_270_0_60, 85, G__get_linked_tagnum(&G__TempDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__TempDict_270_0_61, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__TempDict_270_0_62, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TempDict_270_0_63, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TempDict_270_0_64, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TempInterlock::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TempDict_270_0_65, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TempInterlock::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TempDict_270_0_66, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TempInterlock::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TempDict_270_0_67, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TempInterlock::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TempInterlock", 1471, G__TempDict_270_0_68, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTempDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTempDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTempDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TempDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TempDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TempDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR = { "iterator<random_access_iterator_tag,char,long,char*,char&>" , 115 , -1 };
G__linked_taginfo G__TempDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__TempDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__TempDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__TempDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__TempDictLN_TempInterlock = { "TempInterlock" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTempDict() {
  G__TempDictLN_TClass.tagnum = -1 ;
  G__TempDictLN_TBuffer.tagnum = -1 ;
  G__TempDictLN_TMemberInspector.tagnum = -1 ;
  G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR.tagnum = -1 ;
  G__TempDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__TempDictLN_string.tagnum = -1 ;
  G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__TempDictLN_TList.tagnum = -1 ;
  G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__TempDictLN_TQObjSender.tagnum = -1 ;
  G__TempDictLN_TempInterlock.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTempDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TempDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TempDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TempDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_string);
   G__get_linked_tagnum_fwd(&G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_TList);
   G__get_linked_tagnum_fwd(&G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__TempDictLN_TQObjSender);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TempDictLN_TempInterlock),sizeof(TempInterlock),-1,34048,"needed for the ROOT dict",G__setup_memvarTempInterlock,G__setup_memfuncTempInterlock);
}
extern "C" void G__cpp_setupTempDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTempDict()");
  G__set_cpp_environmentTempDict();
  G__cpp_setup_tagtableTempDict();

  G__cpp_setup_inheritanceTempDict();

  G__cpp_setup_typetableTempDict();

  G__cpp_setup_memvarTempDict();

  G__cpp_setup_memfuncTempDict();
  G__cpp_setup_globalTempDict();
  G__cpp_setup_funcTempDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTempDict();
  return;
}
class G__cpp_setup_initTempDict {
  public:
    G__cpp_setup_initTempDict() { G__add_setup_func("TempDict",(G__incsetup)(&G__cpp_setupTempDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTempDict() { G__remove_setup_func("TempDict"); }
};
G__cpp_setup_initTempDict G__cpp_setup_initializerTempDict;

