/********************************************************************
* TempDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TempDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevTempDict();
extern G__DLLEXPORT void G__set_cpp_environmentTempDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableTempDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceTempDict();
extern G__DLLEXPORT void G__cpp_setup_typetableTempDict();
extern G__DLLEXPORT void G__cpp_setup_memvarTempDict();
extern G__DLLEXPORT void G__cpp_setup_globalTempDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncTempDict();
extern G__DLLEXPORT void G__cpp_setup_funcTempDict();
extern G__DLLEXPORT void G__cpp_setupTempDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TempInterlock.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TempDictLN_TClass;
extern G__linked_taginfo G__TempDictLN_TBuffer;
extern G__linked_taginfo G__TempDictLN_TMemberInspector;
extern G__linked_taginfo G__TempDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__TempDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TempDictLN_string;
extern G__linked_taginfo G__TempDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TempDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__TempDictLN_TList;
extern G__linked_taginfo G__TempDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TempDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__TempDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__TempDictLN_TQObjSender;
extern G__linked_taginfo G__TempDictLN_TempInterlock;

/* STUB derived class for protected member access */
