/********************************************************************
* tti_RQSDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tti_RQSDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevtti_RQSDict();
extern G__DLLEXPORT void G__set_cpp_environmenttti_RQSDict();
extern G__DLLEXPORT void G__cpp_setup_tagtabletti_RQSDict();
extern G__DLLEXPORT void G__cpp_setup_inheritancetti_RQSDict();
extern G__DLLEXPORT void G__cpp_setup_typetabletti_RQSDict();
extern G__DLLEXPORT void G__cpp_setup_memvartti_RQSDict();
extern G__DLLEXPORT void G__cpp_setup_globaltti_RQSDict();
extern G__DLLEXPORT void G__cpp_setup_memfunctti_RQSDict();
extern G__DLLEXPORT void G__cpp_setup_functti_RQSDict();
extern G__DLLEXPORT void G__cpp_setuptti_RQSDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "tti_RQSignals.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__tti_RQSDictLN_TClass;
extern G__linked_taginfo G__tti_RQSDictLN_TBuffer;
extern G__linked_taginfo G__tti_RQSDictLN_TMemberInspector;
extern G__linked_taginfo G__tti_RQSDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__tti_RQSDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__tti_RQSDictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__tti_RQSDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__tti_RQSDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__tti_RQSDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__tti_RQSDictLN_TList;
extern G__linked_taginfo G__tti_RQSDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__tti_RQSDictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__tti_RQSDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__tti_RQSDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__tti_RQSDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__tti_RQSDictLN_TQObjSender;
extern G__linked_taginfo G__tti_RQSDictLN_sig;
extern G__linked_taginfo G__tti_RQSDictLN_tti_RQSignals;

/* STUB derived class for protected member access */
