//
// File generated by C:\ROOT-5.34\\bin\rootcint.exe at Mon Aug 19 14:38:57 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TTiDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TTiDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void tti_CPX400_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_tti_CPX400(void *p);
   static void deleteArray_tti_CPX400(void *p);
   static void destruct_tti_CPX400(void *p);
   static void streamer_tti_CPX400(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::tti_CPX400*)
   {
      ::tti_CPX400 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::tti_CPX400 >(0);
      static ::ROOT::TGenericClassInfo 
         instance("tti_CPX400", ::tti_CPX400::Class_Version(), "./tti_new.h", 37,
                  typeid(::tti_CPX400), DefineBehavior(ptr, ptr),
                  &::tti_CPX400::Dictionary, isa_proxy, 0,
                  sizeof(::tti_CPX400) );
      instance.SetDelete(&delete_tti_CPX400);
      instance.SetDeleteArray(&deleteArray_tti_CPX400);
      instance.SetDestructor(&destruct_tti_CPX400);
      instance.SetStreamerFunc(&streamer_tti_CPX400);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::tti_CPX400*)
   {
      return GenerateInitInstanceLocal((::tti_CPX400*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::tti_CPX400*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *tti_CPX400::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *tti_CPX400::Class_Name()
{
   return "tti_CPX400";
}

//______________________________________________________________________________
const char *tti_CPX400::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::tti_CPX400*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int tti_CPX400::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::tti_CPX400*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void tti_CPX400::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::tti_CPX400*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *tti_CPX400::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::tti_CPX400*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void tti_CPX400::Streamer(TBuffer &R__b)
{
   // Stream an object of class tti_CPX400.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      fQObject.Streamer(R__b);
      R__b >> t1;
      R__b >> samplingTime;
      { TString R__str; R__str.Streamer(R__b); name = R__str.Data(); }
      { TString R__str; R__str.Streamer(R__b); modell = R__str.Data(); }
      R__b >> SerialNumber;
      { TString R__str; R__str.Streamer(R__b); version = R__str.Data(); }
      R__b >> numberOfChannels;
      R__b.CheckByteCount(R__s, R__c, tti_CPX400::IsA());
   } else {
      R__c = R__b.WriteVersion(tti_CPX400::IsA(), kTRUE);
      fQObject.Streamer(R__b);
      R__b << t1;
      R__b << samplingTime;
      { TString R__str = name.c_str(); R__str.Streamer(R__b);}
      { TString R__str = modell.c_str(); R__str.Streamer(R__b);}
      R__b << SerialNumber;
      { TString R__str = version.c_str(); R__str.Streamer(R__b);}
      R__b << numberOfChannels;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void tti_CPX400::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class tti_CPX400.
      typedef ::tti_CPX400 msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*t1", &t1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "samplingTime", &samplingTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "name", (void*)&name);
      R__insp.InspectMember("string", (void*)&name, "name.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "modell", (void*)&modell);
      R__insp.InspectMember("string", (void*)&modell, "modell.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SerialNumber", &SerialNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "version", (void*)&version);
      R__insp.InspectMember("string", (void*)&version, "version.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numberOfChannels", &numberOfChannels);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_tti_CPX400(void *p) {
      delete ((::tti_CPX400*)p);
   }
   static void deleteArray_tti_CPX400(void *p) {
      delete [] ((::tti_CPX400*)p);
   }
   static void destruct_tti_CPX400(void *p) {
      typedef ::tti_CPX400 current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_tti_CPX400(TBuffer &buf, void *obj) {
      ((::tti_CPX400*)obj)->::tti_CPX400::Streamer(buf);
   }
} // end of namespace ROOT for class ::tti_CPX400

/********************************************************
* TTiDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTTiDict();

extern "C" void G__set_cpp_environmentTTiDict() {
  G__add_ipath("../../include");
  G__cpp_reset_tagtableTTiDict();
}
#include <new>
extern "C" int G__cpp_dllrevTTiDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* tti_CPX400 */
static int G__TTiDict_330_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const tti_CPX400*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((tti_CPX400*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((tti_CPX400*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((tti_CPX400*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((tti_CPX400*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((tti_CPX400*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((tti_CPX400*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((tti_CPX400*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((tti_CPX400*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((tti_CPX400*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((tti_CPX400*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   tti_CPX400* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new tti_CPX400((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) tti_CPX400((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TTiDictLN_tti_CPX400));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((tti_CPX400*) G__getstructoffset())->getPort();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((tti_CPX400*) G__getstructoffset())->getVoltage((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((tti_CPX400*) G__getstructoffset())->getActualVoltage((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((tti_CPX400*) G__getstructoffset())->getCurrent((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((tti_CPX400*) G__getstructoffset())->getActualCurrent((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((tti_CPX400*) G__getstructoffset())->getOverVoltageProtection((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((tti_CPX400*) G__getstructoffset())->getOverCurrentProtection((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((tti_CPX400*) G__getstructoffset())->getStatus((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((tti_CPX400*) G__getstructoffset())->getID();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((tti_CPX400*) G__getstructoffset())->getID_TString();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->getSerialNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((tti_CPX400*) G__getstructoffset())->getSerialNumber_str();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((tti_CPX400*) G__getstructoffset())->getSerialNumber_TString();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((tti_CPX400*) G__getstructoffset())->getAddress();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((tti_CPX400*) G__getstructoffset())->getAddress_TString();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->enable((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->disable((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->setStatus((int) G__int(libp->para[0]), (bool) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->setVoltage((int) G__int(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->setOverVoltageProtection((int) G__int(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->setCurrent((int) G__int(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->setOverCurrentProtection((int) G__int(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->setDeltaVoltage((int) G__int(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->GetNumberOfChannels());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->disconnect();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      tti_CPX400::WhatClassAmI();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->startThread());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->stopThread((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((tti_CPX400*) G__getstructoffset())->stopThread());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->showSignals();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->show_errors();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) tti_CPX400::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) tti_CPX400::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) tti_CPX400::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      tti_CPX400::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const tti_CPX400*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((tti_CPX400*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) tti_CPX400::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) tti_CPX400::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) tti_CPX400::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTiDict_330_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) tti_CPX400::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef tti_CPX400 G__Ttti_CPX400;
static int G__TTiDict_330_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (tti_CPX400*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((tti_CPX400*) (soff+(sizeof(tti_CPX400)*i)))->~G__Ttti_CPX400();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (tti_CPX400*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((tti_CPX400*) (soff))->~G__Ttti_CPX400();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* tti_CPX400 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTTiDict {
 public:
  G__Sizep2memfuncTTiDict(): p(&G__Sizep2memfuncTTiDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTTiDict::*p)();
};

size_t G__get_sizep2memfuncTTiDict()
{
  G__Sizep2memfuncTTiDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTTiDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTTiDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("iterator<iterator_traits<string::iterator>::iterator_category,iterator_traits<string::iterator>::value_type,iterator_traits<string::iterator>::difference_type,iterator_traits<string::iterator>::pointer,iterator_traits<string::iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long,char*>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<string::const_iterator>::iterator_category,iterator_traits<string::const_iterator>::value_type,iterator_traits<string::const_iterator>::difference_type,iterator_traits<string::const_iterator>::pointer,iterator_traits<string::const_iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__TTiDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TString,allocator<TString> >::iterator>::iterator_category,iterator_traits<vector<TString,allocator<TString> >::iterator>::value_type,iterator_traits<vector<TString,allocator<TString> >::iterator>::difference_type,iterator_traits<vector<TString,allocator<TString> >::iterator>::pointer,iterator_traits<vector<TString,allocator<TString> >::iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TString>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TString,long>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TString,long,TString*>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TString,allocator<TString> >::const_iterator>::iterator_category,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::value_type,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::difference_type,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::pointer,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* tti_CPX400 */
static void G__setup_memvartti_CPX400(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TTiDictLN_tti_CPX400));
   { tti_CPX400 *p; p=(tti_CPX400*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TTiDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TTiDictLN_TThread),-1,-1,1,"t1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->samplingTime)-(long)(p)),105,0,0,-1,-1,-1,1,"samplingTime=",0,"in Milliseconds");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TTiDictLN_string),-1,-1,4,"name=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TTiDictLN_string),-1,-1,4,"modell=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"SerialNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TTiDictLN_string),-1,-1,4,"version=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"numberOfChannels=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TTiDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTTiDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfunctti_CPX400(void) {
   /* tti_CPX400 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TTiDictLN_tti_CPX400));
   G__memfunc_setup("GetListOfSignals",1602,G__TTiDict_330_0_1, 85, G__get_linked_tagnum(&G__TTiDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__TTiDict_330_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__TTiDict_330_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__TTiDict_330_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__TTiDict_330_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__TTiDict_330_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__TTiDict_330_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__TTiDict_330_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__TTiDict_330_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__TTiDict_330_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("tti_CPX400",815,G__TTiDict_330_0_26, 105, G__get_linked_tagnum(&G__TTiDictLN_tti_CPX400), -1, 0, 1, 1, 1, 0, "C - - 10 - Port", "Constructor: it needs to know the name of the port. up to now there is only one constructor defined. ", (void*) NULL, 0);
   G__memfunc_setup("getPort",741,G__TTiDict_330_0_27, 117, G__get_linked_tagnum(&G__TTiDictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getVoltage",1042,G__TTiDict_330_0_28, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - Channel", "Returns the set voltage of ", (void*) NULL, 0);
   G__memfunc_setup("getActualVoltage",1644,G__TTiDict_330_0_29, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "Returns the output ", (void*) NULL, 0);
   G__memfunc_setup("getCurrent",1059,G__TTiDict_330_0_30, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "Returns the set current limit ", (void*) NULL, 0);
   G__memfunc_setup("getActualCurrent",1661,G__TTiDict_330_0_31, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "Returns the output ", (void*) NULL, 0);
   G__memfunc_setup("getOverVoltageProtection",2517,G__TTiDict_330_0_32, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "Returns the voltage trip setting ", (void*) NULL, 0);
   G__memfunc_setup("getOverCurrentProtection",2534,G__TTiDict_330_0_33, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "Returns the current trip ", (void*) NULL, 0);
   G__memfunc_setup("getStatus",964,G__TTiDict_330_0_34, 103, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "Returns output <channel> on/off status. ", (void*) NULL, 0);
   G__memfunc_setup("getID",461,G__TTiDict_330_0_35, 117, G__get_linked_tagnum(&G__TTiDictLN_string), -1, 0, 0, 1, 1, 0, "", "Returns the instrument identification.", (void*) NULL, 0);
   G__memfunc_setup("getID_TString",1271,G__TTiDict_330_0_36, 117, G__get_linked_tagnum(&G__TTiDictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getSerialNumber",1545,G__TTiDict_330_0_37, 105, -1, -1, 0, 0, 1, 1, 0, "", "returns the serial number of the device", (void*) NULL, 0);
   G__memfunc_setup("getSerialNumber_str",1985,G__TTiDict_330_0_38, 117, G__get_linked_tagnum(&G__TTiDictLN_string), -1, 0, 0, 1, 1, 0, "", "returns the serial number of the device as string", (void*) NULL, 0);
   G__memfunc_setup("getSerialNumber_TString",2355,G__TTiDict_330_0_39, 117, G__get_linked_tagnum(&G__TTiDictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getAddress",1030,G__TTiDict_330_0_40, 117, G__get_linked_tagnum(&G__TTiDictLN_string), -1, 0, 0, 1, 1, 0, "", "Returns the bus address of the ", (void*) NULL, 0);
   G__memfunc_setup("getAddress_TString",1840,G__TTiDict_330_0_41, 117, G__get_linked_tagnum(&G__TTiDictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("enable",615,G__TTiDict_330_0_42, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "enables output <channel>", (void*) NULL, 0);
   G__memfunc_setup("disable",724,G__TTiDict_330_0_43, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - channel", "disables output <channel>", (void*) NULL, 0);
   G__memfunc_setup("setStatus",976,G__TTiDict_330_0_44, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - channel g - - 0 - on_off", "set output <channel> on/off where <on_off> has the following meaning: 0=OFF, 1=ON", (void*) NULL, 0);
   G__memfunc_setup("setVoltage",1054,G__TTiDict_330_0_45, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - channel d - - 0 - Voltage", "Set output <channel> to <Voltage> Volts", (void*) NULL, 0);
   G__memfunc_setup("setOverVoltageProtection",2529,G__TTiDict_330_0_46, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - channel d - - 0 - voltage", "Set output <channel> over voltage protection trip point to <voltage> Volts", (void*) NULL, 0);
   G__memfunc_setup("setCurrent",1071,G__TTiDict_330_0_47, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - channel d - - 0 - current", "Set output <channel> current limit to <current> Amps", (void*) NULL, 0);
   G__memfunc_setup("setOverCurrentProtection",2546,G__TTiDict_330_0_48, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - channel d - - 0 - current", "Set output <channel> over current protection trip point to <current> Amps", (void*) NULL, 0);
   G__memfunc_setup("setDeltaVoltage",1544,G__TTiDict_330_0_49, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - channel d - - 0 - voltage", "Set the output <channel> voltage step size to <voltage> Volts", (void*) NULL, 0);
   G__memfunc_setup("GetNumberOfChannels",1898,G__TTiDict_330_0_50, 105, -1, -1, 0, 0, 1, 1, 0, "", "Returns the Numbers of Channels that the tti device provides.", (void*) NULL, 0);
   G__memfunc_setup("disconnect",1066,G__TTiDict_330_0_51, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WhatClassAmI",1153,G__TTiDict_330_0_52, 121, -1, -1, 0, 0, 3, 1, 0, "", "shows Informations about the class", (void*) G__func2void( (void (*)())(&tti_CPX400::WhatClassAmI) ), 0);
   G__memfunc_setup("startThread",1158,G__TTiDict_330_0_53, 105, -1, -1, 0, 0, 1, 1, 0, "", "starts a thread that will emit the actual voltage and current in a certain time interval ", (void*) NULL, 0);
   G__memfunc_setup("stopThread",1054,G__TTiDict_330_0_54, 105, -1, -1, 0, 1, 1, 1, 0, "g - - 0 '1' waitForEnd", "Stops the thread. if waitForEnd is 1 by default it will wait until the thread is stop. if waitForEnd is 0 it just send a message to the thread that it should stop. ", (void*) NULL, 0);
   G__memfunc_setup("showSignals",1170,G__TTiDict_330_0_55, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("show_errors",1213,G__TTiDict_330_0_56, 121, -1, -1, 0, 0, 1, 1, 0, "", "displays the error list in the command line", (void*) NULL, 0);
   G__memfunc_setup("tti_CPX400",815,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__TTiDictLN_tti_CPX400), -1, 0, 1, 1, 4, 0, "u 'tti_CPX400' - 11 - -", "disabling the copy constructor since one cannot copy the com ports", (void*) NULL, 0);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__TTiDictLN_tti_CPX400), -1, 1, 1, 1, 4, 0, "u 'tti_CPX400' - 11 - -", "disabling assign for the same reson.", (void*) NULL, 0);
   G__memfunc_setup("getCommand",1023,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__TTiDictLN_string), -1, 0, 3, 1, 4, 0, 
"u 'string' - 0 - command1 i - - 0 - channel "
"u 'string' - 0 - command2", "standard get Command ", (void*) NULL, 0);
   G__memfunc_setup("setCommand",1035,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 3, 1, 4, 0, 
"u 'string' - 0 - command i - - 0 - channel "
"d - - 0 - vlaue", "standard set command ", (void*) NULL, 0);
   G__memfunc_setup("ActualVoltageCh1",1544,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "d - - 0 - volt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ActualVoltageCh2",1545,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "d - - 0 - volt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ActualCurrentCh1",1561,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "d - - 0 - current", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ActualCurrentCh2",1562,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "d - - 0 - current", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TTiDict_330_0_65, 85, G__get_linked_tagnum(&G__TTiDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&tti_CPX400::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TTiDict_330_0_66, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&tti_CPX400::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TTiDict_330_0_67, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&tti_CPX400::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TTiDict_330_0_68, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&tti_CPX400::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__TTiDict_330_0_69, 85, G__get_linked_tagnum(&G__TTiDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__TTiDict_330_0_70, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__TTiDict_330_0_71, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TTiDict_330_0_72, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TTiDict_330_0_73, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&tti_CPX400::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TTiDict_330_0_74, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&tti_CPX400::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TTiDict_330_0_75, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&tti_CPX400::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TTiDict_330_0_76, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&tti_CPX400::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~tti_CPX400", 941, G__TTiDict_330_0_77, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTTiDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTTiDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTTiDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TTiDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR = { "iterator<random_access_iterator_tag,char,long,char*,char&>" , 115 , -1 };
G__linked_taginfo G__TTiDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_TThread = { "TThread" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR = { "iterator<random_access_iterator_tag,TString,long,TString*,TString&>" , 115 , -1 };
G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__TTiDictLN_tti_CPX400 = { "tti_CPX400" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTTiDict() {
  G__TTiDictLN_TClass.tagnum = -1 ;
  G__TTiDictLN_TBuffer.tagnum = -1 ;
  G__TTiDictLN_TMemberInspector.tagnum = -1 ;
  G__TTiDictLN_TString.tagnum = -1 ;
  G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR.tagnum = -1 ;
  G__TTiDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__TTiDictLN_string.tagnum = -1 ;
  G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__TTiDictLN_TList.tagnum = -1 ;
  G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__TTiDictLN_TQObjSender.tagnum = -1 ;
  G__TTiDictLN_TThread.tagnum = -1 ;
  G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR.tagnum = -1 ;
  G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__TTiDictLN_tti_CPX400.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTTiDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TTiDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_TString);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_string);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_TList);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_TThread);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR);
   G__get_linked_tagnum_fwd(&G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TTiDictLN_tti_CPX400),sizeof(tti_CPX400),-1,36352,"needed for the ROOT dict",G__setup_memvartti_CPX400,G__setup_memfunctti_CPX400);
}
extern "C" void G__cpp_setupTTiDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTTiDict()");
  G__set_cpp_environmentTTiDict();
  G__cpp_setup_tagtableTTiDict();

  G__cpp_setup_inheritanceTTiDict();

  G__cpp_setup_typetableTTiDict();

  G__cpp_setup_memvarTTiDict();

  G__cpp_setup_memfuncTTiDict();
  G__cpp_setup_globalTTiDict();
  G__cpp_setup_funcTTiDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTTiDict();
  return;
}
class G__cpp_setup_initTTiDict {
  public:
    G__cpp_setup_initTTiDict() { G__add_setup_func("TTiDict",(G__incsetup)(&G__cpp_setupTTiDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTTiDict() { G__remove_setup_func("TTiDict"); }
};
G__cpp_setup_initTTiDict G__cpp_setup_initializerTTiDict;

