/********************************************************************
* TTiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TTiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevTTiDict();
extern G__DLLEXPORT void G__set_cpp_environmentTTiDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableTTiDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceTTiDict();
extern G__DLLEXPORT void G__cpp_setup_typetableTTiDict();
extern G__DLLEXPORT void G__cpp_setup_memvarTTiDict();
extern G__DLLEXPORT void G__cpp_setup_globalTTiDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncTTiDict();
extern G__DLLEXPORT void G__cpp_setup_funcTTiDict();
extern G__DLLEXPORT void G__cpp_setupTTiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "tti_new.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTiDictLN_TClass;
extern G__linked_taginfo G__TTiDictLN_TBuffer;
extern G__linked_taginfo G__TTiDictLN_TMemberInspector;
extern G__linked_taginfo G__TTiDictLN_TString;
extern G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__TTiDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TTiDictLN_string;
extern G__linked_taginfo G__TTiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__TTiDictLN_TList;
extern G__linked_taginfo G__TTiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__TTiDictLN_TQObjSender;
extern G__linked_taginfo G__TTiDictLN_TThread;
extern G__linked_taginfo G__TTiDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTiDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR;
extern G__linked_taginfo G__TTiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__TTiDictLN_tti_CPX400;

/* STUB derived class for protected member access */
